version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mariadb:11
    env_file:
      - .env
    environment:
      MARIADB_DATABASE: LandingPageDB
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_USER: Administrator
      MARIADB_PASSWORD: AdministratorPass
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d

volumes:
  db_data:
